### ISSUE TITLE
k8s-audit: panic on SIGINT

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/plugins#183]
**Describe the bug**
If the falco pod running with the k8s-audit plugins receives a `SIGINT` signal the k8s-audit plugin does not gracefully shutdown but panics.

```bash
Fri Oct 21 08:47:09 2022: Falco version: 0.33.0 (x86_64)
Fri Oct 21 08:47:09 2022: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Oct 21 08:47:09 2022: Loading plugin 'k8saudit' from file /usr/share/falco/plugins/libk8saudit.so
Fri Oct 21 08:47:09 2022: Loading plugin 'json' from file /usr/share/falco/plugins/libjson.so
Fri Oct 21 08:47:09 2022: Loading rules from file /etc/falco/k8s_audit_rules.yaml
Fri Oct 21 08:47:09 2022: Loading rules from file /etc/falco/falco_rules.yaml
Fri Oct 21 08:47:09 2022: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Oct 21 08:47:09 2022: Starting health webserver with threadiness 2, listening on port 8765
Fri Oct 21 08:47:09 2022: Enabled event sources: k8s_audit, syscall
Fri Oct 21 08:47:09 2022: Opening capture with plugin 'k8saudit'
Fri Oct 21 08:47:09 2022: Opening capture with Kernel module
Fri Oct 21 08:50:23 2022: SIGINT received, exiting...
Syscall event drop monitoring:
   - event drop detected: 0 occurrences
   - num times actions taken: 0
2022/10/21 08:50:23 http: panic serving 172.17.0.1:2674: send on closed channel
goroutine 942 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x7f3678354320, 0x7f3678395568})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/falcosecurity/plugins/plugins/k8saudit/pkg/k8saudit.(*Plugin).OpenWebServer.func1({0x7f36783977f0, 0xc000b3d420}, 0xc000c26300)
	/home/prow/go/src/github.com/falcosecurity/plugins/plugins/k8saudit/pkg/k8saudit/source.go:126 +0x371
net/http.HandlerFunc.ServeHTTP(0x200?, {0x7f36783977f0?, 0xc000b3d420?}, 0xc000c83aa8?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0005986a0?, {0x7f36783977f0, 0xc000b3d420}, 0xc000c26300)
	/usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x7f3678396cb0?}, {0x7f36783977f0, 0xc000b3d420}, 0xc000c26300)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000b7e3c0, {0x7f3678397a78, 0xc000097980})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

**How to reproduce it**
I have encountered this behavior each time the kubelet kills the falco pod when the liveness probe is not correctly configured.

**Expected behaviour**

The plugin should properly handle the `SIGINT` signal.

**Comment by robinlandstrom** [comment]
I've noticed the same crash.

But in my case I do have a livenessProbe configured and it ran without issue for a couple of days. But it seems like falco k8s-audit plugin do not manage to keep up with incoming audit log flow. The `send on closed channel` panic message is repeated 1011 times for different goroutines in the log. 

I'll create a separate issue for the performance issues, I get about 120MB of audit logs per hour from an AKS cluster. 

Liveness probe on k8s deployment:
``` yaml
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthz
    port: 8765
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 5
```

Crash logs:
```
2022-11-03T13:33:21+0000: Falco version: 0.33.0 (x86_64)
2022-11-03T13:33:21+0000: CLI args: /usr/bin/falco --disable-source=syscall -o libs_logger.enabled=true -o libs_logger.severity=trace                                                     
2022-11-03T13:33:21+0000: Falco initialized with configuration file: /etc/falco/falco.yaml                                                                                                                                             2022-11-03T13:33:21+0000: Loading plugin 'k8saudit' from file /usr/share/falco/plugins/libk8saudit.so
...
2022-11-03T13:33:21+0000: Configured rules filenames:
2022-11-03T13:33:21+0000:    /etc/falco/k8s_audit_rules.yaml
2022-11-03T13:33:21+0000:    /etc/falco/k8s_audit_rules.z.local.yaml
2022-11-03T13:33:21+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml
2022-11-03T13:33:21+0000: Loading rules from file /etc/falco/k8s_audit_rules.z.local.yaml
2022-11-03T13:33:21+0000: Watching /etc/falco/falco.yaml
2022-11-03T13:33:21+0000: Watching /etc/falco/k8s_audit_rules.yaml
2022-11-03T13:33:21+0000: Watching /etc/falco/k8s_audit_rules.z.local.yaml
2022-11-03T13:33:21+0000: Starting health webserver with threadiness 2, listening on port 8765
2022-11-03T13:33:21+0000: Enabled event sources: k8s_audit
2022-11-03T13:33:21+0000: Opening event source 'k8s_audit'
2022-11-03T13:33:21+0000: Opening capture with plugin 'k8saudit'
2022-11-03T13:33:21+0000: [libs]: Trying to open the right engine!
2022-11-03T13:36:16+0000: [libs]: Flushing thread table
2022-11-03T13:36:16+0000: [libs]: Flushing container table
2022-11-03T13:36:54+0000: [libs]: Flushing container table
...
{"hostname":"falco-aks-audit-d7bd74899-l4clx","output":"2022-11-05T02:11:46.788108000+0000: Notice Attach/Exec to pod (user= REDACTED}}
2022-11-06T01:46:06+0000: [libs]: Flushing thread table
2022-11-06T01:46:10+0000: [libs]: Flushing container table
2022-11-06T01:46:28+0000: [libs]: Flushing container table
2022-11-06T01:52:25+0000: [libs]: Flushing container table
2022-11-06T01:52:44+0000: [libs]: Flushing container table
2022-11-06T01:58:43+0000: [libs]: Flushing container table
2022-11-06T02:01:21+0000: [libs]: Flushing container table
2022-11-06T02:05:00+0000: [libs]: Flushing container table
2022-11-06T02:07:42+0000: [libs]: Flushing container table
2022-11-06T02:08:20+0000: SIGINT received, exiting...
2022-11-06T02:08:20+0000: Closing event source 'k8s_audit'
2022/11/06 02:08:20 http: panic serving 10.244.9.230:40656: send on closed channel
goroutine 4449 [running]:
net/http.(*conn).serve.func1()
    /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x7f3306cbf320, 0x7f3306d00568})
    /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/falcosecurity/plugins/plugins/k8saudit/pkg/k8saudit.(*Plugin).OpenWebServer.func1({0x7f3306d027f0, 0xc003052460}, 0xc002de0d00)
    /home/prow/go/src/github.com/falcosecurity/plugins/plugins/k8saudit/pkg/k8saudit/source.go:126 +0x371
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7f3306d027f0?, 0xc003052460?}, 0xc003233e30?)
    /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x7f3306d027f0, 0xc003052460}, 0xc002de0d00)
    /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x7f3306d01cb0?}, {0x7f3306d027f0, 0xc003052460}, 0xc002de0d00)
    /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000c3540, {0x7f3306d02a78, 0xc000095980})
    /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:3071 +0x4db
2022/11/06 02:08:20 http: panic serving 10.244.9.230:53720: send on closed channel
goroutine 4936 [running]:
net/http.(*conn).serve.func1()
    /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x7f3306cbf320, 0x7f3306d00568})
    /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/falcosecurity/plugins/plugins/k8saudit/pkg/k8saudit.(*Plugin).OpenWebServer.func1({0x7f3306d027f0, 0xc00282f500}, 0xc0020c7c00)
    /home/prow/go/src/github.com/falcosecurity/plugins/plugins/k8saudit/pkg/k8saudit/source.go:126 +0x371
net/http.HandlerFunc.ServeHTTP(0x7f3306cb0e80?, {0x7f3306d027f0?, 0xc00282f500?}, 0xc003f2fc40?)
    /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x7f3306d027f0, 0xc00282f500}, 0xc0020c7c00)
    /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x7f3306d01cb0?}, {0x7f3306d027f0, 0xc00282f500}, 0xc0020c7c00)
    /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00304f540, {0x7f3306d02a78, 0xc000095980})
    /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:3071 +0x4db
2022/11/06 02:08:20 http: panic serving 10.244.9.230:51168: send on closed channel
...
```
